#!/bin/sh
HERE="$(dirname "$(readlink -f "$0")")"
export CODECAFE_ATLAS_HOME="${XDG_DATA_HOME:-$HOME/.local/share}/CodeCafe-Atlas"
mkdir -p "$CODECAFE_ATLAS_HOME"
exec "$HERE/usr/bin/CodeCafe-Atlas/CodeCafe-Atlas" "$@"
